default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: react-rails-training_development

test:
  <<: *default
  database: react-rails-training_test

production:
  <<: *default
  database: react-rails-training_production
  username: react-rails-training
  password: <%= ENV['REACT-RAILS-TRAINING_DATABASE_PASSWORD'] %>
